development:
  adapter: postgresql
  encoding: utf8
  database: faithlycfc_development
  pool: 5
  username: 
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: faithlycfc_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: faithly_production
  pool: 5
  username: 
  password:
  